const fs = require('fs');
var opts = require("minimist")(process.argv.slice(2));

if (!opts.f || typeof opts.f !== "string") {
  console.log("use -f to specify your mapping.json path");
  return;
}


fs.readFile(opts.f, 'utf8', (err, data) => {
    if (err) {
        console.error('Error reading file:', err);
        return;
    }

    try {
        const mapping = JSON.parse(data);

        console.log("# ----------------------------------------------------------------------------------------------");
        console.log("#  Copyright (c) 2026 Tomlin7. All rights reserved.");
        console.log("#  Licensed under the MIT License. See License.txt in the project root for license information.");
        console.log("# ----------------------------------------------------------------------------------------------");
        console.log("");
        console.log("# This file is automatically generated by (microsoft/vscode-codicons)/scripts/export-to-py.js");
        console.log("# Please don't edit it, as your changes will be overwritten.");
        console.log("");
        console.log("from enum import StrEnum");
        console.log("");
        console.log("");
        console.log("class Icons(StrEnum):");

        // New format: mapping is { "code": ["alias1", "alias2", ...] }
        Object.entries(mapping).forEach(([code, aliases]) => {
            const codeValue = parseInt(code);
            const unicodeEscape = decimalToUnicodeEscape(codeValue);

            // Register each alias with the same code
            aliases.forEach((name) => {
                console.log(`    ${toSnakeCase(name).toUpperCase()} = "${unicodeEscape}"`);
            });
        });

    } catch (error) {
        console.error('Error parsing JSON:', error);
    }
});


function toSnakeCase(name) {
    return name.replace(/-/g, '_');
}

function decimalToUnicodeEscape(decimal) {
    return '\\u' + decimal.toString(16).padStart(4, '0');
}
